<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:atl="http://www.eclipse.org/gmt/2005/ATL" xmlns:ocl="http://www.eclipse.org/gmt/2005/OCL">
  <atl:Module name="families2persons">
    <commentsBefore>-- @atlcompiler atl2006</commentsBefore>
    <inModels name="families_model" metamodel="/1"/>
    <outModels name="persons_model" metamodel="/2"/>
    <elements xsi:type="atl:MatchedRule" name="father2male">
      <commentsBefore>-- Comments -> This is a MatchedRule: father2male -> </commentsBefore>
      <outPattern>
        <elements xsi:type="atl:SimpleOutPatternElement" varName="male_out">
          <type xsi:type="ocl:OclModelElement" name="Male" model="/2"/>
          <bindings propertyName="fullName">
            <value xsi:type="ocl:NavigationOrAttributeCallExp" name="getFatherName()">
              <source xsi:type="ocl:VariableExp" referredVariable="/3"/>
            </value>
          </bindings>
        </elements>
      </outPattern>
      <inPattern>
        <elements xsi:type="atl:SimpleInPatternElement" varName="father_in">
          <type xsi:type="ocl:OclModelElement" name="Father" model="/1"/>
        </elements>
      </inPattern>
    </elements>
    <elements xsi:type="atl:MatchedRule" name="mother2female">
      <commentsBefore>-- Comments -> This is a MatchedRule: mother2female -> </commentsBefore>
      <outPattern>
        <elements xsi:type="atl:SimpleOutPatternElement" varName="female_out">
          <type xsi:type="ocl:OclModelElement" name="Female" model="/2"/>
          <bindings propertyName="fullName">
            <value xsi:type="ocl:OperatorCallExp" operationName="+">
              <source xsi:type="ocl:NavigationOrAttributeCallExp" name="firstName">
                <source xsi:type="ocl:VariableExp" referredVariable="/4"/>
              </source>
              <arguments xsi:type="ocl:NavigationOrAttributeCallExp" name="familyMother.lastName">
                <source xsi:type="ocl:VariableExp" referredVariable="/5"/>
              </arguments>
            </value>
          </bindings>
        </elements>
      </outPattern>
      <inPattern>
        <elements xsi:type="atl:SimpleInPatternElement" varName="mother_in">
          <type xsi:type="ocl:OclModelElement" name="Mother" model="/1"/>
        </elements>
      </inPattern>
    </elements>
    <elements xsi:type="atl:MatchedRule" name="son2male">
      <commentsBefore>-- Comments -> This is a MatchedRule: son2male -> </commentsBefore>
      <outPattern>
        <elements xsi:type="atl:SimpleOutPatternElement" varName="male_out">
          <type xsi:type="ocl:OclModelElement" name="Male" model="/2"/>
          <bindings propertyName="fullName">
            <value xsi:type="ocl:OperatorCallExp" operationName="+">
              <source xsi:type="ocl:NavigationOrAttributeCallExp" name="firstName">
                <source xsi:type="ocl:VariableExp" referredVariable="/6"/>
              </source>
              <arguments xsi:type="ocl:NavigationOrAttributeCallExp" name="familySon.lastName">
                <source xsi:type="ocl:VariableExp" referredVariable="/7"/>
              </arguments>
            </value>
          </bindings>
        </elements>
      </outPattern>
      <inPattern>
        <elements xsi:type="atl:SimpleInPatternElement" varName="son_in">
          <type xsi:type="ocl:OclModelElement" name="Son" model="/1"/>
        </elements>
      </inPattern>
    </elements>
    <elements xsi:type="atl:MatchedRule" name="daughter2female">
      <commentsBefore>-- Comments -> This is a MatchedRule: daughter2female -> </commentsBefore>
      <outPattern>
        <elements xsi:type="atl:SimpleOutPatternElement" varName="female_out">
          <type xsi:type="ocl:OclModelElement" name="Female" model="/2"/>
          <bindings propertyName="fullName">
            <value xsi:type="ocl:OperatorCallExp" operationName="+">
              <source xsi:type="ocl:NavigationOrAttributeCallExp" name="firstName">
                <source xsi:type="ocl:VariableExp" referredVariable="/8"/>
              </source>
              <arguments xsi:type="ocl:NavigationOrAttributeCallExp" name="familyDaughter.lastName">
                <source xsi:type="ocl:VariableExp" referredVariable="/9"/>
              </arguments>
            </value>
          </bindings>
        </elements>
      </outPattern>
      <inPattern>
        <elements xsi:type="atl:SimpleInPatternElement" varName="daughter_in">
          <type xsi:type="ocl:OclModelElement" name="Daughter" model="/1"/>
        </elements>
      </inPattern>
    </elements>
    <elements xsi:type="atl:Helper">
      <commentsBefore>-- Comments -> This is a Helper: getFatherName()</commentsBefore>
      <commentsAfter>-- Body: self.firstName + ' ' + self.familyFather.lastName</commentsAfter>
      <definition>
        <feature xsi:type="ocl:Operation" name="getFatherName()">
          <returnType xsi:type="ocl:StringType"/>
        </feature>
        <context_>
          <context_ xsi:type="ocl:OclModelElement" name="Father" model="/10"/>
        </context_>
      </definition>
    </elements>
  </atl:Module>
  <ocl:OclModel name="families" elements="/0/@elements.0/@inPattern/@elements.0/@type /0/@elements.1/@inPattern/@elements.0/@type /0/@elements.2/@inPattern/@elements.0/@type /0/@elements.3/@inPattern/@elements.0/@type" model="/0/@inModels.0"/>
  <ocl:OclModel name="persons" elements="/0/@elements.0/@outPattern/@elements.0/@type /0/@elements.1/@outPattern/@elements.0/@type /0/@elements.2/@outPattern/@elements.0/@type /0/@elements.3/@outPattern/@elements.0/@type" model="/0/@outModels.0"/>
  <ocl:VariableDeclaration varName="father_in" variableExp="/0/@elements.0/@outPattern/@elements.0/@bindings.0/@value/@source"/>
  <ocl:VariableDeclaration varName="mother_in" variableExp="/0/@elements.1/@outPattern/@elements.0/@bindings.0/@value/@source/@source"/>
  <ocl:VariableDeclaration varName="mother_in" variableExp="/0/@elements.1/@outPattern/@elements.0/@bindings.0/@value/@arguments.0/@source"/>
  <ocl:VariableDeclaration varName="son_in" variableExp="/0/@elements.2/@outPattern/@elements.0/@bindings.0/@value/@source/@source"/>
  <ocl:VariableDeclaration varName="son_in" variableExp="/0/@elements.2/@outPattern/@elements.0/@bindings.0/@value/@arguments.0/@source"/>
  <ocl:VariableDeclaration varName="daughter_in" variableExp="/0/@elements.3/@outPattern/@elements.0/@bindings.0/@value/@source/@source"/>
  <ocl:VariableDeclaration varName="daughter_in" variableExp="/0/@elements.3/@outPattern/@elements.0/@bindings.0/@value/@arguments.0/@source"/>
  <ocl:OclModel name="families" elements="/0/@elements.4/@definition/@context_/@context_"/>
</xmi:XMI>
