<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="mwcore" nsURI="mwcore">
    <eClassifiers xsi:type="ecore:EClass" name="WElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          unique="false" lowerBound="1" eType="#/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
          unique="false" lowerBound="1" eType="#/1/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="model" ordered="false"
          lowerBound="1" eType="#/0/WModel" eOpposite="#/0/WModel/ownedElement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WModel" abstract="true" eSuperTypes="#/0/WElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElement" upperBound="-1"
          eType="#/0/WElement" derived="true" containment="true" eOpposite="#/0/WElement/model">
        <eAnnotations source="relations"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="wovenModel" ordered="false"
          lowerBound="1" upperBound="-1" eType="#/0/WModelRef" derived="true" containment="true">
        <eAnnotations source="inputModel,outputModel"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WRef" abstract="true" eSuperTypes="#/0/WElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" ordered="false"
          unique="false" lowerBound="1" eType="#/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WModelRef" abstract="true" eSuperTypes="#/0/WRef">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElementRef" ordered="false"
          upperBound="-1" eType="#/0/WElementRef" containment="true" eOpposite="#/0/WElementRef/modelRef"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WElementRef" abstract="true" eSuperTypes="#/0/WRef">
      <eStructuralFeatures xsi:type="ecore:EReference" name="modelRef" ordered="false"
          lowerBound="1" eType="#/0/WModelRef" eOpposite="#/0/WModelRef/ownedElementRef"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WAssociation" abstract="true" eSuperTypes="#/0/WElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="associationEnd" ordered="false"
          lowerBound="1" upperBound="-1" eType="#/0/WAssociationEnd" containment="true"
          eOpposite="#/0/WAssociationEnd/association"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WAssociationEnd" abstract="true" eSuperTypes="#/0/WElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="association" ordered="false"
          lowerBound="1" eType="#/0/WAssociation" eOpposite="#/0/WAssociation/associationEnd"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="relatedLink" ordered="false"
          lowerBound="1" eType="#/0/WLink"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WLink" abstract="true" eSuperTypes="#/0/WElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="child" upperBound="-1"
          eType="#/0/WLink" derived="true" containment="true" eOpposite="#/0/WLink/parent">
        <eAnnotations source="relations"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" ordered="false"
          lowerBound="1" eType="#/0/WLink" eOpposite="#/0/WLink/child"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="end" ordered="false"
          lowerBound="1" upperBound="-1" eType="#/0/WLinkEnd" derived="true" containment="true"
          eOpposite="#/0/WLinkEnd/link">
        <eAnnotations source="source,target,source,target,source,target,source,target,source,target"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WLinkEnd" abstract="true" eSuperTypes="#/0/WElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="link" ordered="false"
          lowerBound="1" eType="#/0/WLink" eOpposite="#/0/WLink/end"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="element" ordered="false"
          lowerBound="1" eType="#/0/WElementRef"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes" nsURI="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean" instanceClassName="java.lang.Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer" instanceClassName="java.lang.Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
  </ecore:EPackage>
  <ecore:EPackage name="mmw_metagem" nsURI="mmw_metagem">
    <eClassifiers xsi:type="ecore:EEnum" name="MyAttributeType">
      <eLiterals name="copy" value="1"/>
      <eLiterals name="concatenation" value="2"/>
      <eLiterals name="varius" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="MyTypeElem">
      <eLiterals name="MyEclassifier" value="1"/>
      <eLiterals name="MyEattribute" value="2"/>
      <eLiterals name="MyEreference" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModelRoot" eSuperTypes="#/0/WModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="inputModel" ordered="false"
          lowerBound="1" upperBound="-1" eType="#/2/InModelTransf" containment="true">
        <eAnnotations source="wovenModel"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outputModel" ordered="false"
          lowerBound="1" upperBound="-1" eType="#/2/OutModelTransf" containment="true">
        <eAnnotations source="wovenModel"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="relations" ordered="false"
          lowerBound="1" upperBound="-1" eType="#/2/Relations" containment="true">
        <eAnnotations source="ownedElement"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModelTransf" abstract="true" eSuperTypes="#/0/WModelRef">
      <eAnnotations source="welementRefType:TransformationElementRef&#x9;"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InModelTransf" eSuperTypes="#/2/ModelTransf">
      <eAnnotations source="welementRefType:TransformationElementRef"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OutModelTransf" eSuperTypes="#/2/ModelTransf">
      <eAnnotations source="welementRefType:TransformationElementRef"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TransformationElementRef" eSuperTypes="#/0/WElementRef">
      <eAnnotations source="wmodelRefType:ModelTransf"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Relations" abstract="true" eSuperTypes="#/0/WLink">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeAttri" ordered="false"
          unique="false" lowerBound="1" eType="#/2/MyAttributeType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeE" ordered="false"
          unique="false" lowerBound="1" eType="#/2/MyTypeElem"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMain" ordered="false"
          unique="false" lowerBound="1" eType="#/1/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" ordered="false"
          unique="false" lowerBound="1" eType="#/1/Boolean" defaultValueLiteral=""/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InElement" eSuperTypes="#/0/WLinkEnd">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="guardCondition" ordered="false"
          unique="false" lowerBound="1" eType="#/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OutElement" eSuperTypes="#/0/WLinkEnd">
      <eStructuralFeatures xsi:type="ecore:EReference" name="relations" ordered="false"
          lowerBound="1" upperBound="-1" eType="#/2/Relations" containment="true">
        <eAnnotations source="child"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OneToOne" eSuperTypes="#/2/Relations">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
          lowerBound="1" eType="#/2/InElement" containment="true">
        <eAnnotations source="end"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
          lowerBound="1" eType="#/2/OutElement" containment="true">
        <eAnnotations source="end"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OneToZero" eSuperTypes="#/2/Relations">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
          lowerBound="1" eType="#/2/InElement" containment="true">
        <eAnnotations source="end"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ZeroToOne" eSuperTypes="#/2/Relations">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
          lowerBound="1" eType="#/2/OutElement" containment="true">
        <eAnnotations source="end"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OneToMany" eSuperTypes="#/2/Relations">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
          lowerBound="1" eType="#/2/InElement" containment="true">
        <eAnnotations source="end"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
          lowerBound="1" upperBound="-1" eType="#/2/OutElement" containment="true">
        <eAnnotations source="end"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ManyToOne" eSuperTypes="#/2/Relations">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
          lowerBound="1" upperBound="-1" eType="#/2/InElement" containment="true">
        <eAnnotations source="end"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
          lowerBound="1" eType="#/2/OutElement" containment="true">
        <eAnnotations source="end"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ManyToMany" eSuperTypes="#/2/Relations">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
          lowerBound="1" upperBound="-1" eType="#/2/InElement" containment="true">
        <eAnnotations source="end"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
          lowerBound="1" upperBound="-1" eType="#/2/OutElement" containment="true">
        <eAnnotations source="end"/>
      </eStructuralFeatures>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
