/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package metagem.provider;

import java.util.ArrayList;
import java.util.Collection;

import metagem.util.MetagemAdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class MetagemItemProviderAdapterFactory extends MetagemAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public MetagemItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link metagem.ModelRoot} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModelRootItemProvider modelRootItemProvider;

	/**
	 * This creates an adapter for a {@link metagem.ModelRoot}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModelRootAdapter() {
		if (modelRootItemProvider == null) {
			modelRootItemProvider = new ModelRootItemProvider(this);
		}

		return modelRootItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link metagem.SourceModelTransf} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SourceModelTransfItemProvider sourceModelTransfItemProvider;

	/**
	 * This creates an adapter for a {@link metagem.SourceModelTransf}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSourceModelTransfAdapter() {
		if (sourceModelTransfItemProvider == null) {
			sourceModelTransfItemProvider = new SourceModelTransfItemProvider(this);
		}

		return sourceModelTransfItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link metagem.TargetModelTransf} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TargetModelTransfItemProvider targetModelTransfItemProvider;

	/**
	 * This creates an adapter for a {@link metagem.TargetModelTransf}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTargetModelTransfAdapter() {
		if (targetModelTransfItemProvider == null) {
			targetModelTransfItemProvider = new TargetModelTransfItemProvider(this);
		}

		return targetModelTransfItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link metagem.OneToOne} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OneToOneItemProvider oneToOneItemProvider;

	/**
	 * This creates an adapter for a {@link metagem.OneToOne}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOneToOneAdapter() {
		if (oneToOneItemProvider == null) {
			oneToOneItemProvider = new OneToOneItemProvider(this);
		}

		return oneToOneItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link metagem.OneToZero} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OneToZeroItemProvider oneToZeroItemProvider;

	/**
	 * This creates an adapter for a {@link metagem.OneToZero}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOneToZeroAdapter() {
		if (oneToZeroItemProvider == null) {
			oneToZeroItemProvider = new OneToZeroItemProvider(this);
		}

		return oneToZeroItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link metagem.ZeroToOne} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ZeroToOneItemProvider zeroToOneItemProvider;

	/**
	 * This creates an adapter for a {@link metagem.ZeroToOne}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createZeroToOneAdapter() {
		if (zeroToOneItemProvider == null) {
			zeroToOneItemProvider = new ZeroToOneItemProvider(this);
		}

		return zeroToOneItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link metagem.OneToMany} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OneToManyItemProvider oneToManyItemProvider;

	/**
	 * This creates an adapter for a {@link metagem.OneToMany}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOneToManyAdapter() {
		if (oneToManyItemProvider == null) {
			oneToManyItemProvider = new OneToManyItemProvider(this);
		}

		return oneToManyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link metagem.ManyToOne} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ManyToOneItemProvider manyToOneItemProvider;

	/**
	 * This creates an adapter for a {@link metagem.ManyToOne}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createManyToOneAdapter() {
		if (manyToOneItemProvider == null) {
			manyToOneItemProvider = new ManyToOneItemProvider(this);
		}

		return manyToOneItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link metagem.ManyToMany} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ManyToManyItemProvider manyToManyItemProvider;

	/**
	 * This creates an adapter for a {@link metagem.ManyToMany}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createManyToManyAdapter() {
		if (manyToManyItemProvider == null) {
			manyToManyItemProvider = new ManyToManyItemProvider(this);
		}

		return manyToManyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link metagem.SourceElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SourceElementItemProvider sourceElementItemProvider;

	/**
	 * This creates an adapter for a {@link metagem.SourceElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSourceElementAdapter() {
		if (sourceElementItemProvider == null) {
			sourceElementItemProvider = new SourceElementItemProvider(this);
		}

		return sourceElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link metagem.TargetElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TargetElementItemProvider targetElementItemProvider;

	/**
	 * This creates an adapter for a {@link metagem.TargetElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTargetElementAdapter() {
		if (targetElementItemProvider == null) {
			targetElementItemProvider = new TargetElementItemProvider(this);
		}

		return targetElementItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (modelRootItemProvider != null) modelRootItemProvider.dispose();
		if (sourceModelTransfItemProvider != null) sourceModelTransfItemProvider.dispose();
		if (targetModelTransfItemProvider != null) targetModelTransfItemProvider.dispose();
		if (oneToOneItemProvider != null) oneToOneItemProvider.dispose();
		if (oneToZeroItemProvider != null) oneToZeroItemProvider.dispose();
		if (zeroToOneItemProvider != null) zeroToOneItemProvider.dispose();
		if (oneToManyItemProvider != null) oneToManyItemProvider.dispose();
		if (manyToOneItemProvider != null) manyToOneItemProvider.dispose();
		if (manyToManyItemProvider != null) manyToManyItemProvider.dispose();
		if (sourceElementItemProvider != null) sourceElementItemProvider.dispose();
		if (targetElementItemProvider != null) targetElementItemProvider.dispose();
	}

}
