<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ORDB4ORA"
    nsURI="http:///ORDB4ORA.ecore" nsPrefix="ORDB4ORA">
  <eClassifiers xsi:type="ecore:EClass" name="ANSICharacterType" eSuperTypes="#//ANSIType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Descriptor" lowerBound="1"
        eType="#//ANSICharacterTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ANSICharacterTypes">
    <eLiterals name="CHARACTER" literal="CHARACTER"/>
    <eLiterals name="CHARACTERVARYING" value="1" literal="CHARACTERVARYING"/>
    <eLiterals name="CHARVARYING" value="2" literal="CHARVARYING"/>
    <eLiterals name="NCHARVARYING" value="3" literal="NCHARVARYING"/>
    <eLiterals name="VARCHAR" value="4" literal="VARCHAR"/>
    <eLiterals name="NATIONALCHARACTER" value="5" literal="NATIONALCHARACTER"/>
    <eLiterals name="NATIONALCHAR" value="6" literal="NATIONALCHAR"/>
    <eLiterals name="NATIONALCHARACTERVARYING" value="7" literal="NATIONALCHARACTERVARYING"/>
    <eLiterals name="NATIONALCHARVARYING" value="8" literal="NATIONALCHARVARYING"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ANSINumberType" eSuperTypes="#//ANSIType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Descriptor" lowerBound="1"
        eType="#//ANSINumberTypes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Precision" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Scale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ANSINumberTypes">
    <eLiterals name="NUMERIC" literal="NUMERIC"/>
    <eLiterals name="DECIMAL" value="1" literal="DECIMAL"/>
    <eLiterals name="DEC" value="2" literal="DEC"/>
    <eLiterals name="INTEGER" value="3" literal="INTEGER"/>
    <eLiterals name="INT" value="4"/>
    <eLiterals name="SMALLINT" value="5"/>
    <eLiterals name="FLOAT" value="6"/>
    <eLiterals name="DOUBLEPRECISION" value="7"/>
    <eLiterals name="REAL" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ANSIType" abstract="true" eSuperTypes="#//BasicDataType"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnyType" eSuperTypes="#//SuppliedType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Descriptor" lowerBound="1"
        eType="#//SuppliedAnyTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//StructuralComponent">
    <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
      <details key="NotEmptyType" value="not self.Type.oclIsUndefined()"/>
      <details key="LegalBuiltInCharacterValues" value="if self.Type.oclIsTypeOf(BuiltInCharacterType) then&#xD;&#xA;&#x9;self.features->select(f|f.key = 'Size' or f.key = 'Semantic')->size()=self.features.size()&#xD;&#xA;else&#xD;&#xA;true&#xD;&#xA;endif"/>
      <details key="LegalBuiltInNumberValues" value="if self.Type.oclIsTypeOf(BuiltInNumberType) then&#xD;&#xA;&#x9;self.features->select(f|f.key = 'Presicion' or f.key = 'Scale')->size()=self.features.size()&#xD;&#xA;else&#xD;&#xA;true&#xD;&#xA;endif"/>
      <details key="LegalLongAndRawValues" value="if self.Type.oclIsTypeOf(LongAndRawType) then&#xD;&#xA;&#x9;if(self.Type.Descriptor='#RAW')&#xD;&#xA;&#x9;&#x9;self.features->select()(f|f.key = 'Size')->size()=self.features.size()&#xD;&#xA;&#x9;else&#xD;&#xA;&#x9;&#x9;true&#xD;&#xA;&#x9;endif&#xD;&#xA;else&#xD;&#xA;true&#xD;&#xA;endif"/>
      <details key="LegalTimestampValues" value="if self.Type.oclIsTypeOf(DatetimeType)  then&#xD;&#xA;&#x9;if(self.Type.Descriptor='#TIMESTAMP' or self.Type.Descriptor='#TIMESTAMPWITHTIMEZONE'  or self.Type.Descriptor='#TIMESTAMPWITHLOCALTIMEZONE')&#xD;&#xA;&#x9;&#x9;self.features->select(f|f.key = 'Second_Presicion')->size()=self.features.size()&#xD;&#xA;&#x9;else&#xD;&#xA;&#x9;&#x9;true&#xD;&#xA;&#x9;endif&#xD;&#xA;else&#xD;&#xA;&#x9;true&#xD;&#xA;endif"/>
      <details key="LegalIntervalValues" value="if self.Type.oclIsTypeOf(DatetimeType)  then&#xD;&#xA;&#x9;if(self.Type.Descriptor='#INTERVALYEARTOMONTH' or self.Type.Descriptor='#INTERVALDAYTOSECOND')&#xD;&#xA;&#x9;&#x9;self.features->select(f|f.key = 'Day_Presicion' or f.key = 'Year_Presicion' or  f.key = 'Second_Presicion')->size()=self.features.size()&#xD;&#xA;&#x9;else&#xD;&#xA;&#x9;&#x9;true&#xD;&#xA;&#x9;endif&#xD;&#xA;else&#xD;&#xA;&#x9;true&#xD;&#xA;endif"/>
      <details key="LegalROWValues" value="if self.Type.oclIsTypeOf(ROWIDType)  then&#xD;&#xA;&#x9;if(self.Type.Descriptor='#UROWID')&#xD;&#xA;&#x9;&#x9;self.features->select(f|f.key = 'Size')->size()=self.features.size()&#xD;&#xA;&#x9;else&#xD;&#xA;&#x9;&#x9;true&#xD;&#xA;&#x9;endif&#xD;&#xA;else&#xD;&#xA;&#x9;true&#xD;&#xA;endif"/>
      <details key="LegalANSICharacterValues" value="if self.Type.oclIsTypeOf(ANSICharacterType) then&#xD;&#xA;&#x9;self.features->select(f|f.key = 'Size')->size()=self.features.size()&#xD;&#xA;else&#xD;&#xA;true&#xD;&#xA;endif"/>
      <details key="LegalANSINumberValues" value="if self.Type.oclIsTypeOf(ANSINumberType) then&#xD;&#xA;&#x9;if(self.Type.Descriptor='#NUMERIC' or self.Type.Descriptor='#DECIMAL' or self.Type.Descriptor='#DEC')&#xD;&#xA;&#x9;&#x9;self.features->select(f|f.key = 'Presicion' or f.key = 'Scale')->size()=self.features.size()&#xD;&#xA;&#x9;else&#xD;&#xA;&#x9;&#x9;true&#xD;&#xA;&#x9;endif&#xD;&#xA;else&#xD;&#xA;&#x9;true&#xD;&#xA;endif"/>
      <details key="LegalSmallIntrValues" value="if self.Type.oclIsTypeOf(ANSINumberType) then&#xD;&#xA;&#x9;if(self.Type.Descriptor='#SMALLINT')&#xD;&#xA;&#x9;&#x9;self.features->select(f|f.key = 'Size')->size()=self.features.size()&#xD;&#xA;&#x9;else&#xD;&#xA;&#x9;&#x9;true&#xD;&#xA;&#x9;endif&#xD;&#xA;else&#xD;&#xA;&#x9;true&#xD;&#xA;endif"/>
    </eAnnotations>
    <eOperations name="restriction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/uml2/1.1.0/GenModel">
        <details key="body" value="if not self.Type.oclIsTypeOf(BasicDataType) then self.Size =0 else self.Size >=0 endif"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="if not self.Type.oclIsTypeOf(BasicDataType) then self.Size =0 else self.Size >=0 endif"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="context">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cache of context-specific information."/>
        </eAnnotations>
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structured" eType="#//StructuredType"
        eOpposite="#//StructuredType/attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicDataType" abstract="true" eSuperTypes="#//Datatype"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BuiltInCharacterSemantics">
    <eLiterals name="BYTE"/>
    <eLiterals name="CHAR" value="1" literal="CHAR"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BuiltInCharacterType" eSuperTypes="#//BuiltInType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Descriptor" lowerBound="1"
        eType="#//BuiltInCharacterTypes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Semantic" eType="#//BuiltInCharacterSemantics"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Size_Min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Size_Max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Size_Def" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BuiltInCharacterTypes">
    <eLiterals name="CHAR" literal="CHAR"/>
    <eLiterals name="VARCHAR2" value="1" literal="VARCHAR2"/>
    <eLiterals name="NCHAR" value="2" literal="NCHAR"/>
    <eLiterals name="NVARCHAR2" value="3" literal="NVARCHAR2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BuiltInDatetimeTypes">
    <eLiterals name="DATE" literal="DATE"/>
    <eLiterals name="TIMESTAMP" value="1" literal="TIMESTAMP"/>
    <eLiterals name="TIMESTAMPWITHTIMEZONE" value="2" literal="TIMESTAMPWITHTIMEZONE"/>
    <eLiterals name="TIMESTAMPWITHLOCALTIMEZONE" value="3" literal="TIMESTAMPWITHLOCALTIMEZONE"/>
    <eLiterals name="INTERVALYEARTOMONTH" value="4" literal="INTERVALYEARTOMONTH"/>
    <eLiterals name="INTERVALDAYTOSECOND" value="5" literal="INTERVALDAYTOSECOND"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BuiltInLOBType">
    <eLiterals name="BLOB" literal="BLOB"/>
    <eLiterals name="CLOB" value="1"/>
    <eLiterals name="NLOB" value="2"/>
    <eLiterals name="BFILE" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BuiltInLongAndRawTypes">
    <eLiterals name="LONG" literal="LONG"/>
    <eLiterals name="LONGRAW" value="1" literal="LONGRAW"/>
    <eLiterals name="RAW" value="2" literal="RAW"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BuiltInNumberType" eSuperTypes="#//BuiltInType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Descriptor" lowerBound="1"
        eType="#//BuiltNumberTypes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Precision_Mn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Precision_Max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Scale_Min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Scale_Max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BuiltInROWIDType">
    <eLiterals name="ROWID" literal="ROWID"/>
    <eLiterals name="UROWID" value="1" literal="UROWID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BuiltInType" abstract="true" eSuperTypes="#//BasicDataType"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BuiltNumberTypes">
    <eLiterals name="NUMBER" literal="NUMBER"/>
    <eLiterals name="BINARY_FLOAT" value="1"/>
    <eLiterals name="BINARY_DOUBLE" value="2" literal="BINARY_DOUBLE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CharacterFeature" instanceClassName="java.util.Map$Entry"
      eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="#//CharacterFeatures"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CharacterFeatures">
    <eLiterals name="size" literal="size"/>
    <eLiterals name="semantic" value="1" literal="semantic"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Check" eSuperTypes="#//Restriction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&lt;&lt;check>>"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Column" eSuperTypes="#//StructuralComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" lowerBound="1" eType="#//Table"
        eOpposite="#//Table/columns"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Datatype" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//Model"
        eOpposite="#//Model/datatype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatetimeFeature" instanceClassName="java.util.Map$Entry"
      eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="#//DatetimeFeatures"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DatetimeFeatures">
    <eLiterals name="precision" literal="precision"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatetimeType" eSuperTypes="#//BuiltInType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Descriptor" lowerBound="1"
        eType="#//BuiltInDatetimeTypes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SecondPrecision_Min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SecondPrecision_Max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SecondPrecision_Def" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DayPrecision_Min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DayPrecision_Max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DayPrecision_Def" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="YearPrecision_Min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="YearPrecision_Max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="YearPrecision_Def" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ForeignKey" eSuperTypes="#//Restriction">
    <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
      <details key="LegalAttributes" value="if (self.attribute->select(a|a.Type.oclIsKindOf(BasicDataType) or a.Type.oclIsTypeOf(ReferenceType)&#xD;&#xA;)->size() = self.attribute.size()) then&#xD;&#xA;&#x9;self.attribute->select(a|a.Type.oclIsKindOf(ReferenceType))->&#xD;&#xA;&#x9;select(a|a.Type.Descriptor='#LONG' or&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;   a.Type.Descriptor='#LONGRAW' or&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;   a.Type.Descriptor='#TIEMSTAMPWITHTIMEZONE' or&#xD;&#xA;                                             a.Type.oclIsTypeOf(LOBType) &#xD;&#xA;)->size() + self.attribute->select(a|a.Type.oclIsKindOf(ReferenceType))->size() = self.attribute.size()&#x9;&#xD;&#xA;else&#xD;&#xA;&#x9;false&#xD;&#xA;endif"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="&lt;&lt;fk>>"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="OnDelete" eType="#//ONDELETEActions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" lowerBound="1"
        eType="#//Table"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Return" lowerBound="1"
        eType="#//Datatype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntervalFeature" instanceClassName="java.util.Map$Entry"
      eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="#//IntervalFeatures"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IntervalFeatures">
    <eLiterals name="day_precision" literal="day_precision"/>
    <eLiterals name="second_precision" value="1" literal="second_precision"/>
    <eLiterals name="year_precision" value="2" literal="year_precision"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LOBType" eSuperTypes="#//BuiltInType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Descriptor" ordered="false"
        lowerBound="1" eType="#//BuiltInLOBType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LongAndRawType" eSuperTypes="#//BuiltInType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Descriptor" lowerBound="1"
        eType="#//BuiltInLongAndRawTypes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Size_Min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Size_Max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MediaType" eSuperTypes="#//SuppliedType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Descriptor" lowerBound="1"
        eType="#//SuppliedMediaTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MergingStructuredType" eSuperTypes="#//StructuredType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="compositors" upperBound="-1"
        eType="#//StructuredType" eOpposite="#//StructuredType/composes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Method">
    <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
      <details key="NotEmptyName" value="self.Name.size()>0"/>
      <details key="NotEmptyType" value="not self.returnType.oclIsUndefined()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="override" ordered="false"
        eType="#//Method"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structured" eType="#//StructuredType"
        eOpposite="#//StructuredType/method"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//MethodParameter" containment="true" eOpposite="#//MethodParameter/method"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" lowerBound="1"
        eType="#//Datatype"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Body" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodParameter" eSuperTypes="#//Parameter">
    <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
      <details key="NotEmptyName" value="self.Name.size()>0"/>
      <details key="NotEmptyType" value="not self.Type.oclIsUndefined()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="method" eType="#//Method"
        eOpposite="#//Method/parameters"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
      <details key="NotEmptyName" value="self.Name.size()>0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datatype" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//Datatype" containment="true" eOpposite="#//Datatype/model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" ordered="false"
        upperBound="-1" eType="#//Table" containment="true" eOpposite="#//Table/model"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" upperBound="-1"
        eType="#//Operation" containment="true" eOpposite="#//Operation/model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" upperBound="-1"
        eType="#//Package" containment="true" eOpposite="#//Package/model"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NestedTableType" eSuperTypes="#//Datatype">
    <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
      <details key="NotEmptyName" value="self.Name.size()>0"/>
      <details key="NotEmptyType" value="not self.Type.oclIsUndefined()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="&lt;&lt;nt>>"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Type" ordered="false" lowerBound="1"
        eType="#//Datatype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NotNull" eSuperTypes="#//Restriction">
    <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
      <details key="LegalAttributes" value="self.attribute->select(a|a.Type.oclIsKindOf(BasicDataType) or&#xD;&#xA;     &#x9;&#x9;&#x9;&#x9;&#x9;&#x9; a.Type.oclIsTypeOf(StructuredType) or&#xD;&#xA;     &#x9;&#x9;&#x9;&#x9;&#x9;&#x9; a.Type.oclIsTypeOf(Varray) or&#xD;&#xA;     &#x9;&#x9;&#x9;&#x9;&#x9;&#x9; a.Type.oclIsTypeOf(ReferenceType)&#xD;&#xA;)->size() = self.attribute.size()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="&lt;&lt;not null>>"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumberFeature" instanceClassName="java.util.Map$Entry"
      eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="#//NumberFeatures"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NumberFeatures">
    <eLiterals name="size" literal="size"/>
    <eLiterals name="precision" value="1" literal="precision"/>
    <eLiterals name="scale" value="2" literal="scale"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ONDELETEActions">
    <eLiterals name="CASCADE" literal="CASCADE"/>
    <eLiterals name="SETNULL" value="1" literal="SET NULL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Body" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationParameters" upperBound="-1"
        eType="#//OperationParameter" containment="true" eOpposite="#//OperationParameter/operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//Model"
        eOpposite="#//Model/operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" eType="#//Package"
        eOpposite="#//Package/operations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationParameter" eSuperTypes="#//Parameter">
    <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
      <details key="NotEmptyName" value="self.Name.size()>0"/>
      <details key="NotEmptyType" value="not self.Type.oclIsUndefined()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Mode" eType="#//ParameterMode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="#//Operation"
        eOpposite="#//Operation/operationParameters"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//Operation" containment="true" eOpposite="#//Operation/package"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//Model"
        eOpposite="#//Model/package"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
      <details key="NotEmptyName" value="self.Name.size()>0"/>
      <details key="NotEmptyType" value="not self.Type.oclIsUndefined()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Type" lowerBound="1" eType="#//Datatype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParameterMode">
    <eLiterals name="IN" literal="IN"/>
    <eLiterals name="OUT" value="1" literal="OUT"/>
    <eLiterals name="INOUT" value="2" literal="IN OUT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimaryKey" eSuperTypes="#//Restriction">
    <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
      <details key="LegalAttributes" value="if (self.attribute->select(a|a.Type.oclIsKindOf(BasicDataType)&#xD;&#xA;)->size() = self.attribute.size()) then&#xD;&#xA;&#x9;self.attribute->select(a|a.Type.Descriptor='#LONG' or&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;   a.Type.Descriptor='#LONGRAW' or&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;   a.Type.Descriptor='#TIEMSTAMPWITHTIMEZONE' or&#xD;&#xA;                                             a.Type.oclIsTypeOf(LOBType) &#xD;&#xA;)->size() = self.attribute.size()&#x9;&#xD;&#xA;else&#xD;&#xA;&#x9;false&#xD;&#xA;endif"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="&lt;&lt;pk>>"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Procedure" eSuperTypes="#//Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="ROWIDType" eSuperTypes="#//BuiltInType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Descriptor" ordered="false"
        lowerBound="1" eType="#//BuiltInROWIDType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Size_Min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Size_Max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RawFeature" instanceClassName="java.util.Map$Entry"
      eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="#//RawFeatures"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RawFeatures">
    <eLiterals name="size" literal="size"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceType" eSuperTypes="#//Datatype">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="&lt;&lt;ref>>"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Type" ordered="false" lowerBound="1"
        eType="#//StructuredType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Restriction" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//StructuralComponent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" lowerBound="1" eType="#//Table"
        eOpposite="#//Table/restriction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RowFeature" instanceClassName="java.util.Map$Entry"
      eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="#//RowFeatures"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RowFeatures">
    <eLiterals name="size" literal="size"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpacialType" eSuperTypes="#//SuppliedType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Descriptor" lowerBound="1"
        eType="#//SuppliedSpacialTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StoredNestedTable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" ordered="false"
        lowerBound="1" eType="#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typed" eType="#//TypedTable"
        eOpposite="#//TypedTable/storedNested"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuralComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Type" ordered="false" lowerBound="1"
        eType="#//Datatype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Feature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="restrictions" upperBound="-1"
        eType="#//Restriction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuredType" eSuperTypes="#//Datatype">
    <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
      <details key="NotEmptyName" value="self.Name.size()>0"/>
      <details key="CantSelfInherit" value="self.supertype &lt;> self"/>
      <details key="UniqueName" value="self.model.datatype->select(dt | dt.oclIsTypeOf(StructuredType) &#xD;&#xA;                              and (dt &lt;> self))-> select(st | st.Name= self.Name)->size() = 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="&lt;&lt;udt>>"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" ordered="false"
        upperBound="-1" eType="#//Attribute" containment="true" eOpposite="#//Attribute/structured"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="method" ordered="false"
        upperBound="-1" eType="#//Method" containment="true" eOpposite="#//Method/structured"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typed" ordered="false"
        upperBound="-1" eType="#//TypedTable" containment="true" eOpposite="#//TypedTable/structuredType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supertype" ordered="false"
        eType="#//StructuredType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instantiable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="not_final" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composes" eType="#//MergingStructuredType"
        eOpposite="#//MergingStructuredType/compositors"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SuppliedAnyTypes">
    <eLiterals name="SYSANYDATA" literal="SYSANYDATA"/>
    <eLiterals name="SYSANYTYPE" value="1" literal="SYSANYTYPE"/>
    <eLiterals name="SYSANYDATASET" value="2" literal="SYSANYDATASET"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SuppliedMediaTypes">
    <eLiterals name="ORDAudio" literal="ORDAudio"/>
    <eLiterals name="ORDImage" value="1" literal="ORDImage"/>
    <eLiterals name="ORDVideo" value="2" literal="ORDVideo"/>
    <eLiterals name="ORDDoc" value="3" literal="ORDDoc"/>
    <eLiterals name="ORDImageSignature" value="4" literal="ORDImageSignature"/>
    <eLiterals name="SI_STILLIMAGE" value="5" literal="SI_STILLIMAGE"/>
    <eLiterals name="SI_AVERAGECOLOR" value="6"/>
    <eLiterals name="SI_POSITIONALCOLOR" value="7"/>
    <eLiterals name="SI_COLORHISTOGRAM" value="8"/>
    <eLiterals name="SI_TEXTURE" value="9"/>
    <eLiterals name="SI_FEATURELIST" value="10"/>
    <eLiterals name="SI_COLOR" value="11"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SuppliedSpacialTypes">
    <eLiterals name="SDO_GEOMETRY" literal="SDO_GEOMETRY"/>
    <eLiterals name="SDO_TOPO_GEOMETRY" value="1" literal="SDO_TOPO_GEOMETRY"/>
    <eLiterals name="SDO_RASTER" value="2" literal="SDO_RASTER"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SuppliedType" abstract="true" eSuperTypes="#//BasicDataType"/>
  <eClassifiers xsi:type="ecore:EEnum" name="SuppliedXMLTypes">
    <eLiterals name="XMLTYPE" literal="XMLTYPE"/>
    <eLiterals name="URITYPE" value="1" literal="URITYPE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Table">
    <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
      <details key="OnlyOnePrimaryKey" value="self.restriction->select(r|r.oclIsTypeOf(PrimaryKey))->size()&lt;=1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="restriction" ordered="false"
        upperBound="-1" eType="#//Restriction" containment="true" eOpposite="#//Restriction/table"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" ordered="false"
        upperBound="-1" eType="#//Column" containment="true" eOpposite="#//Column/table"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//Model"
        eOpposite="#//Model/table"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggers" upperBound="-1"
        eType="#//Trigger" containment="true" eOpposite="#//Trigger/table"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="views" eType="#//View"
        eOpposite="#//View/tables"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trigger">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Body" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Event" lowerBound="1" upperBound="-1"
        eType="#//TriggerEvent"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Action" lowerBound="1"
        eType="#//TriggerActionTime"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="updateColumns" upperBound="-1"
        eType="#//StructuralComponent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" lowerBound="1" eType="#//Table"
        eOpposite="#//Table/triggers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TriggerActionTime">
    <eLiterals name="BEFORE" literal="BEFORE"/>
    <eLiterals name="AFTER" value="1" literal="AFTER"/>
    <eLiterals name="INSTEADOF" value="2" literal="INSTEAD OF"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TriggerEvent">
    <eLiterals name="DELETE" literal="DELETE"/>
    <eLiterals name="INSERT" value="1" literal="INSERT"/>
    <eLiterals name="UPDATE" value="2" literal="UPDATE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedTable" eSuperTypes="#//Table">
    <eStructuralFeatures xsi:type="ecore:EReference" name="storedNested" ordered="false"
        upperBound="-1" eType="#//StoredNestedTable" containment="true" eOpposite="#//StoredNestedTable/typed"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structuredType" lowerBound="1"
        eType="#//StructuredType" eOpposite="#//StructuredType/typed"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Unique" eSuperTypes="#//Restriction">
    <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
      <details key="LegalAttributes" value="if (self.attribute->select(a|a.Type.oclIsKindOf(BasicDataType)&#xD;&#xA;)->size() = self.attribute.size()) then&#xD;&#xA;&#x9;self.attribute->select(a|a.Type.Descriptor='#LONG' or&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;   a.Type.Descriptor='#LONGRAW' or&#xD;&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;   a.Type.Descriptor='#TIEMSTAMPWITHTIMEZONE' or&#xD;&#xA;                                             a.Type.oclIsTypeOf(LOBType) &#xD;&#xA;)->size() = self.attribute.size()&#x9;&#xD;&#xA;else&#xD;&#xA;&#x9;false&#xD;&#xA;endif"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="&lt;&lt;unique>>"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Varray" eSuperTypes="#//Datatype">
    <eAnnotations source="http://www.eclipse.org/ocl/examples/OCL">
      <details key="NotEmptyName" value="self.Name.size()>0"/>
      <details key="NotEmptyElementsNumber" value="not self.NumElements.oclIsUndefined()"/>
      <details key="NotEmptyType" value="not self.Type.oclIsUndefined()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="&lt;&lt;array>>"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NumElements" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Type" ordered="false" lowerBound="1"
        eType="#//Datatype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="View" eSuperTypes="#//Table">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="query_expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tables" upperBound="-1"
        eType="#//Table" eOpposite="#//Table/views"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XMLType" eSuperTypes="#//SuppliedType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Descriptor" lowerBound="1"
        eType="#//SuppliedXMLTypes"/>
  </eClassifiers>
</ecore:EPackage>
