<?xml version="1.0" encoding="ISO-8859-1"?>
<mm_hybrid:Module xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:mm_hybrid="http:///MM_Hybrid.ecore" name_module="sql2ordb_hybrid">
  <rule name_rule="r1" isMain="true">
    <in name_element="MULTISET"/>
    <out name_element="NestedTableType"/>
  </rule>
  <rule name_rule="r2" isMain="true">
    <in name_element="IntervalTypes"/>
  </rule>
</mm_hybrid:Module>
