<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hybrid"
    nsURI="org.eclipse.kybele.hybrid" nsPrefix="hybrid">
  <eClassifiers xsi:type="ecore:EEnum" name="TypeRelation">
    <eLiterals name="Copy" value="1" literal="Copy"/>
    <eLiterals name="Concatenation" value="2" literal="Concatenation"/>
    <eLiterals name="Other" value="3" literal="Other"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TypeElement">
    <eLiterals name="EClassifier" value="1" literal="EClassifier"/>
    <eLiterals name="EAttribute" value="2" literal="EAttribute"/>
    <eLiterals name="EReference" value="3" literal="EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Datatype">
    <eLiterals name="null" literal="null"/>
    <eLiterals name="Boolean" value="1"/>
    <eLiterals name="Integer" value="2"/>
    <eLiterals name="String" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HybridElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module" eSuperTypes="#//HybridElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//Operation" containment="true" eOpposite="#//Operation/module"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceModels" lowerBound="1"
        upperBound="-1" eType="#//SourceModel" containment="true" eOpposite="#//SourceModel/module"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetModels" lowerBound="1"
        upperBound="-1" eType="#//TargetModel" containment="true" eOpposite="#//TargetModel/module"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" lowerBound="1" upperBound="-1"
        eType="#//Rule" containment="true" eOpposite="#//Rule/module"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//HybridElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" lowerBound="1"
        eType="#//Module" eOpposite="#//Module/operations"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="return" eType="#//OpDefinition"
        containment="true" eOpposite="#//OpDefinition/return_op"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightPattern" eType="#//RightPattern"
        eOpposite="#//RightPattern/operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="#//OpDefinition"
        containment="true" eOpposite="#//OpDefinition/context_op"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//OpArgument" containment="true" eOpposite="#//OpArgument/operation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" eType="#//TransformationElement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="datatype" eType="#//Datatype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context_op" eType="#//Operation"
        eOpposite="#//Operation/context"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="return_op" eType="#//Operation"
        eOpposite="#//Operation/return"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourceModel" eSuperTypes="#//Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" lowerBound="1"
        eType="#//Module" eOpposite="#//Module/sourceModels"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TargetModel" eSuperTypes="#//Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" lowerBound="1"
        eType="#//Module" eOpposite="#//Module/targetModels"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model" abstract="true" eSuperTypes="#//HybridElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type_mm" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule" eSuperTypes="#//HybridElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" lowerBound="1"
        eType="#//Module" eOpposite="#//Module/rules"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMain" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isUnique" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeRelation" lowerBound="1"
        eType="#//TypeRelation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeElement" lowerBound="1"
        eType="#//TypeElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sources" upperBound="-1"
        eType="#//Source" containment="true" eOpposite="#//Source/rule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targets" upperBound="-1"
        eType="#//Target" containment="true" eOpposite="#//Target/rule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="#//Guard"
        containment="true" eOpposite="#//Guard/rule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trace" eType="#//TraceRule"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" eType="#//Rule"
        eOpposite="#//Rule/isExtended"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isExtended" upperBound="-1"
        eType="#//Rule" eOpposite="#//Rule/extends"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightPattern" upperBound="-1"
        eType="#//RightPattern" eOpposite="#//RightPattern/rule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransformationElement" abstract="true"
      eSuperTypes="#//HybridElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="belongsTo" eType="#//TransformationElement"
        eOpposite="#//TransformationElement/owns"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owns" upperBound="-1" eType="#//TransformationElement"
        eOpposite="#//TransformationElement/belongsTo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//Model"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Source" eSuperTypes="#//TransformationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" eType="#//Rule" eOpposite="#//Rule/sources"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightPatternOwned" eType="#//RightPattern"
        eOpposite="#//RightPattern/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceLink" upperBound="-1"
        eType="#//TraceLink" eOpposite="#//TraceLink/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Target" eSuperTypes="#//TransformationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" eType="#//Rule" eOpposite="#//Rule/targets"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
        eType="#//Binding" containment="true" eOpposite="#//Binding/owned"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftPatternOwned" eType="#//LeftPattern"
        eOpposite="#//LeftPattern/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceLink" upperBound="-1"
        eType="#//TraceLink" eOpposite="#//TraceLink/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isRefered" upperBound="-1"
        eType="#//RightPattern" eOpposite="#//RightPattern/reference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Guard">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" lowerBound="1" eType="#//Rule"
        eOpposite="#//Rule/guard"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Binding" eSuperTypes="#//HybridElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owned" lowerBound="1" eType="#//Target"
        eOpposite="#//Target/bindings"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="#//RightPattern"
        containment="true" eOpposite="#//RightPattern/binding"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//LeftPattern"
        containment="true" eOpposite="#//LeftPattern/binding"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeRelation" lowerBound="1"
        eType="#//TypeRelation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeElement" lowerBound="1"
        eType="#//TypeElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trace" eType="#//TraceBinding"
        eOpposite="#//TraceBinding/binding"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RightPattern">
    <eStructuralFeatures xsi:type="ecore:EReference" name="binding" lowerBound="1"
        eType="#//Binding" eOpposite="#//Binding/right"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" upperBound="-1"
        eType="#//Source" containment="true" eOpposite="#//Source/rightPatternOwned"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" upperBound="-1"
        eType="#//Operation" eOpposite="#//Operation/rightPattern"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="concreteValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//Target"
        eOpposite="#//Target/isRefered"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" upperBound="-1" eType="#//Rule"
        eOpposite="#//Rule/rightPattern"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LeftPattern">
    <eStructuralFeatures xsi:type="ecore:EReference" name="binding" lowerBound="1"
        eType="#//Binding" eOpposite="#//Binding/left"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Target"
        containment="true" eOpposite="#//Target/leftPatternOwned"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TraceRule" eSuperTypes="#//TraceLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceBindings" upperBound="-1"
        eType="#//TraceBinding" containment="true" eOpposite="#//TraceBinding/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TraceLink" abstract="true" eSuperTypes="#//HybridElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" upperBound="-1"
        eType="#//Source" eOpposite="#//Source/traceLink"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" upperBound="-1"
        eType="#//Target" eOpposite="#//Target/traceLink"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TraceBinding" eSuperTypes="#//TraceLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//TraceRule"
        eOpposite="#//TraceRule/traceBindings"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="binding" eType="#//Binding"
        eOpposite="#//Binding/trace"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpArgument">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="datatype" eType="#//Datatype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" eType="#//TransformationElement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="#//Operation" eOpposite="#//Operation/arguments"/>
  </eClassifiers>
</ecore:EPackage>
